apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: voting-vs
spec:
  host: voting.od.ro
#  tls:
#    secret:
  upstreams:
  - name: vote
    service: voting-service
    port: 80
  routes:
  - path: /
    action:
      pass: vote
